from circular_linked_list import CircularLinkedList
from doubly_linked_list import DoublyLinkedList

print('Circular linked list')

circular_list = CircularLinkedList()
circular_list.insert_first(1)
circular_list.insert_first(2)
circular_list.insert_first(3)
circular_list.insert_last(4)
circular_list.insert_last(5)
circular_list.delete_first()
circular_list.display_list()

print('Doubly linked list')

doubly_linked_list = DoublyLinkedList()
doubly_linked_list.insert_first(10)
doubly_linked_list.insert_first(20)
doubly_linked_list.insert_first(30)
doubly_linked_list.insert_last(40)
doubly_linked_list.insert_last(50)
doubly_linked_list.delete_last()
doubly_linked_list.delete_last()
doubly_linked_list.delete_first()
doubly_linked_list.insert_first(60)
doubly_linked_list.insert_last(70)
doubly_linked_list.insert_after(10, 80)
doubly_linked_list.insert_after(20, 90)
doubly_linked_list.insert_after(70, 100)
doubly_linked_list.delete_last()
doubly_linked_list.delete_first()
doubly_linked_list.delete_key(20)
doubly_linked_list.delete_key(10)
doubly_linked_list.delete_key(70)
doubly_linked_list.insert_after(90, 110)
doubly_linked_list.insert_after(80, 120)
doubly_linked_list.delete_key(120)
doubly_linked_list.delete_last()
doubly_linked_list.delete_first()
doubly_linked_list.display_list()
doubly_linked_list.delete_key(120)

